from __future__ import annotations

from enum import Enum


class TrackingExecutionKind(str, Enum):
    LEGACY_TARGET_TRACKING = "LEGACY_TARGET_TRACKING"
    EVENT_CANDIDATE_HANDOFF_R1 = "EVENT_CANDIDATE_HANDOFF_R1"


class R1PipelineStage(str, Enum):
    CREATED = "CREATED"
    SELECTED_SHOT_TRACKING = "SELECTED_SHOT_TRACKING"
    WAITING_MEMORY_REVIEW = "WAITING_MEMORY_REVIEW"
    WAITING_CROSS_SHOT_CONFIRMATION = "WAITING_CROSS_SHOT_CONFIRMATION"
    APPLYING_HUMAN_DECISION = "APPLYING_HUMAN_DECISION"
    BUILDING_TARGET_MEMORY = "BUILDING_TARGET_MEMORY"
    SEARCHING_NEXT_SHOT = "SEARCHING_NEXT_SHOT"
    FINALIZING = "FINALIZING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_UNRESOLVED_GAPS = "COMPLETED_WITH_UNRESOLVED_GAPS"
    COMPLETED_SAFE_BLOCK = "COMPLETED_SAFE_BLOCK"
    FAILED = "FAILED"


class R1ProcessingStatus(str, Enum):
    IDLE = "IDLE"
    READY = "READY"
    PROCESSING = "PROCESSING"
    WAITING = "WAITING"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_UNRESOLVED_GAPS = "COMPLETED_WITH_UNRESOLVED_GAPS"
    COMPLETED_SAFE_BLOCK = "COMPLETED_SAFE_BLOCK"
    FAILED = "FAILED"


LEGACY_EXECUTION_KIND = TrackingExecutionKind.LEGACY_TARGET_TRACKING.value
R1_EXECUTION_KIND = TrackingExecutionKind.EVENT_CANDIDATE_HANDOFF_R1.value
